### ISSUE TITLE
get all nodes (w/o toposort)

### ISSUE THREAD

**Issue by matthewmueller** [makojs/tree#1]
not a huge deal, but i'm finding that i want to get a list of nodes in the graph to know what files i need to watch, but i don't need them to be in topological order. 

haven't looked into the ordering algorithm, but it would probably save a few cycles if there could be a method to just return the nodes.

**Comment by dominicbarnes** [comment]
I think it might be good to implement a `Tree#getFiles([options])` that includes an `options.topological` option, as this seems to be a reasonable use-case. (and removes the awkwardly named `Tree#topologicalOrder()`)

**Comment by matthewmueller** [comment]
:+1: yah sounds better

**Comment by dominicbarnes** [comment]
mako-tree 0.6.0 includes this change (and more!)

**Comment by dominicbarnes** [comment]
Once I finish making the changes to js/css this weekend, I'll include this in `mako-core` and will bump minor there and across the board.
