### ISSUE TITLE
Add a global root/base path

### ISSUE THREAD

**Issue by dominicbarnes** [makojs/tree#15]
While I'm generally happy about the latest batch of changes to the tree, I keep getting this nagging feeling that relying on `file.base` for everything leaves a lot of ambiguity that I'm sure is only going to cause problems down the road.

It puts a lot of burden on other plugins to consider `file.base` whenever they are adding new files. Things can be especially tricky if you are mixing and matching different bases throughout the build, as there's not always a clear way to pick a "winner". Most of the solutions I have, while not more than linear in complexity, are still extra work I don't want slowing down builds.

Once I finish this batch of changes to all the core plugins, (only a few more to go!) I'm going to make this change.

@matthewmueller: I'm going to follow your recommendation, and add `root` to the configuration of the `Tree` itself. It will basically superimpose that to every `file.base` that is added to the tree, effectively removing the need for any plugin to ever consider what the root is. (as there will always only be 1)

@darsain: I know this isn't what you were hoping for, but I think I'm just going to make this call now. If you need to use multiple roots in a single project, you'll just need to create 2 separate mako runners, which I don't think is unreasonable or burdensome.

Feel free to comment on this issue in the next day or so before I get around to making this change.

**Comment by darsain** [comment]
Before making builds of multiple files super awkward, lets figure out if there isn't some middle ground, because creating new mako instance for every file about to be build seems wrong, and makes mako's ability to be composed and used multiple times pointless.

So, I thought that any resolved dependency file would just inherit the `base` of the entry file that depends on it. Could you give an example case where this causes issues?

**Comment by dominicbarnes** [comment]
@darsain: you would only need a new instance for each root, not each file. Do you have any use-cases in mind where a project would need multiple roots? I've never once found the complexity of such a build necessary, but I doubt I've considered everything.

The problem is not adding new files/dependencies, you are right when things inherit `base` from their parent. However, the problem comes later, during assembly mostly.

Let's say I add many JS files, with 2 or more roots amongst them. The goal of `mako-js` is to compress all the JS files into 1 for each entry file, so which root should I choose for the final entry? You could probably argue that the clear "winner" is the entry file, but discarding that bit of information from the dependencies could lead to unexpected behavior.

For another example, consider CSS + images. Unlike for JS, when I roll up the tree some dependencies (eg: images) stay behind in the tree. When generating sourcemaps, the relative path becomes the "source file" (eg: `mako://images/logo.jpg`) If there are several roots, it's a lot more likely for collisions to happen here.

Lastly, consider JS/CSS bundling. The goal is to add a new file that holds the dependencies that are shared among 2 or more entries. If there are several roots among the entry files, I can't determine which root should be used by the newly added JS file.

There are more ambiguities than this, and you could probably argue that there are solutions to all of them. However, this puts an even bigger burden on plugin authors to make sure they remember to consider this every time the interact with the tree.

The way I see it, the worst-case scenario for multiple runners per-root is that you are duplicating builds for some files if they are included among files using several roots. Are there any bigger complications that you can think of?

**Comment by darsain** [comment]
Hm... yeah, reading through your examples, one root per instance makes sense, and seems like it'll produce a cleaner API.

I was coming from a perspective of creating a gulp transform stream, where I define a mako instance and run all incoming files (which can have different `file.base`) through it. With global root I'll have to create a new mako instance for each file in the stream. Definitely doable, just a tiny bit awkward.

This one use case definitely doesn't warrant dealing with all the issues you've mentioned, so I'm all for global root now :)

Regarding the behavior, I guess mako will completely ignore `file.base` after the change? Could you at least set it for every file to match the global root? So the file objects could be used in gulp plugins without modifications.

**Comment by dominicbarnes** [comment]
@darsain: mako will not ignore `file.base` at all, it will simply super-impose the global `root` whenever new files are created. (so it will be consistent throughout the entire tree)

Thanks for understanding! I'm sure we can figure out a better solution in the future, but for now I feel like this is the least-risky moving towards 1.0

**Comment by darsain** [comment]
> mako will not ignore `file.base` at all, it will simply super-impose the global `root` whenever new files are created.

Uhm, I don't understand it works now :) Lets say I have this directory structure:

```
foo/
  css/
    a.css
    b.css
  img/
    img.jpg
````

`a.css` depends on `b.css` and `img.jpg`. I do `.build({base: './foo', path: './foo/css/a.css')`.

What is gonna be the base for these files?

**Comment by dominicbarnes** [comment]
@darsain: `base` will be pwd, (ie: `.`) since the default `root` is going to overwrite the `base` you try and set on those files.

In order to set the base as `./foo`, you'll (roughly) need to do `mako('./foo').build('./foo/css/a.css')`.

**Comment by darsain** [comment]
Oh so `entry.base` is ignored, and `file.base` is used only internally. Got it :) Thanks.

**Comment by dominicbarnes** [comment]
@darsain yeah, haha that's a really concise way to put it. Sorry, it's pretty late for me atm. (gonna get some sleep now)
