### ISSUE TITLE
Vinyl 2.0 heads up

### ISSUE THREAD

**Issue by darsain** [makojs/tree#20]
There is Vinyl 2.0 coming hopefully soon with some useful stuff:

- My [PR with path normalization](https://github.com/gulpjs/vinyl/pull/101) got finally merged. Changes:
  - All path properties are now normalized (passed through `path.normalize()`) and have trailing separator removed on set.
  - `file.cwd` and `file.base` are now a get/set objects.
  - Constructor normalizes both `path` and the whole `file.history` when passed.
  - `file.base` now proxies to `file.cwd` when `null`, `undefined`, or equal to `file.cwd`.
- New get/set property `file.symlink` (also normalized and stripped off trailing separator) that points to a symlink target in case the file is a symbolic link.
- New method `file.isSymbolic()` that returns `true` when `file.symlink` is set, and `file.isNull()` is `true`.
- When you pass both `path` and `history` into constructor options, `path` will now be appended to `history`. Previously the presence of `path` would nullify the `history` property.

The path normalization means all paths are consistently normalized, use the correct current platform separator, and never have a trailing one.

Example:

```js
// on windows
file.path = '/foo/bar/../baz/'; // => \\foo\\baz

// on posix
file.path = '/foo/bar/../baz/'; // => /foo/baz
```

This also means that if you are comparing paths and the comparison returns `false`, you can be sure they are not the same. Previously, you could get `false` on paths that point to the same location:

```js
let file1 = new Vinyl({path: '/foo/../bar'});
let file2 = new Vinyl({path: '/bar/'});
let file3 = new Vinyl({path: '/bar'});
file1.path === file2.path; // false
file1.path === file3.path; // false
file2.path === file3.path; // false
```

In Vinyl 2.0, paths above are gonna be consistently normalized to `/bar`, and all comparisons return `true`.

Not even force string concatenation (`dir + '/' + file`) instead of using `path.join()` breaks it. In fact, that is now a pretty viable way how to set path properties if you are too lazy to use `path.jon()` :)

---

*Notable caveat:*

The separator conversion to current platform one doesn't work the other way around though (win sep => posix sep), since `\` is a valid filename character on posix platforms. So:

```js
// on posix
file.path = '\\foo\\bar\\'; // => \\foo\\bar  (trailing separator is still stripped though)
```

For posix platforms this path is a valid filename, and nothing can be done about it without breaking posix compliance.

**Comment by dominicbarnes** [comment]
Nice! I'll be ready to incorporate this once it is released. Any idea what the ETA looks like?

**Comment by darsain** [comment]
No idea, but a lot got done in last few weeks. Looking at the opened issues, it seems like the only things left are some code/repo/tests refactoring.
