### ISSUE TITLE
Creating a new file from an existing file

### ISSUE THREAD

**Issue by matthewmueller** [makojs/tree#32]
Right now it's not really possible to create a new file from an existing file. For example, if I do this:

``` js
let f = file.clone()
f.contents = new Buffer(src)
f.path = path
```

It's treated as a clone, so the ID is the same and it's in the tree already. I think it makes sense to be able to do something like this:

``` js
// file.extend or file.file or file.create make sense too
let f = file.extend({
  path: 'b.txt',
  contents: new Buffer('b')
})

file.addDependency(f) // to actually connect it
```

where a new file is created with a new ID, but uses of the same tree (unconnected initially).

**Comment by dominicbarnes** [comment]
What is the actual use-case here? This seems like something you wouldn't actually do in practice, but I'm not entirely opposed to the idea if it's useful.

**Comment by matthewmueller** [comment]
The use case I have is taking a JS file and compiling it to multiple different targets, ie one for server-side rendering & one to serve on the client.

**Comment by dominicbarnes** [comment]
Ah gotcha, yeah I can see that being useful. How does something like `File#copy(newPath)` sound?

```js
// newPath is relative to the current absolute path?
let clientJS = serverJS.copy('./client.js')
// the new file still needs to be added to the tree
tree.addFile(clientJS)
```

I'm thinking that this "copy" method would do a full clone and generate a new `id` as well. It shouldn't have to do much more, I imagine.

**Comment by dominicbarnes** [comment]
Would you expect a "copy" to also retain the path history? My inclination was to reset it as it's really a new file. But if that's the case, should all the custom properties be copied over too? (where does the line get drawn?)

**Comment by darsain** [comment]
Custom props should definitely get copied, since that might be stuff like `sourceMap`. But on the other hand, it might also be something that should be unique to a given a file. Can't think of an example though.

Maybe this needs some `shouldCopy(prop)` method.

Or maybe lets just copy enumerable props, and if someone wants to define a unique one, let them do it with a non-enumerable descriptor.

**Comment by dominicbarnes** [comment]
Yeah, I'm thinking a good first-step will be to just use `clone()` and override the ID. We'll leave everything else as-is. (including path history, custom props, etc)

**Comment by dominicbarnes** [comment]
This has been added with v1.5.0
